require(quantmod)
require(PerformanceAnalytics)
getSymbols('SPY', from = '1900-01-01')
adSPY <- adjustOHLC(SPY, use.Adjusted=TRUE)
overnightRets <- na.omit(Op(adSPY)/lag(Cl(adSPY)) - 1)
table.AnnualizedReturns(overnightRets)
maxDrawdown(overnightRets)
(avgTrade <- mean(overnightRets))
(avgWin <- mean(overnightRets[overnightRets > 0]))
(avgLoss <- mean(overnightRets[overnightRets < 0]))
(profitFactor <- -sum(overnightRets[overnightRets > 0])/sum(overnightRets[overnightRets < 0]))
SharpeRatio.annualized(overnightRets, Rf = 0, scale = NA, geometric = FALSE)
charts.PerformanceSummary(overnightRets)
